### ISSUE TITLE
GitHub code doesn't match NuGet SAML2.Core 0.9.0 Version

### ISSUE THREAD

**Issue by andresfuentes** [elerch/SAML2#5]
While using the Nuget version I found  that the sample code didn't work one of the things was that the  method AddByMetadataUrl was not available

**Comment by chunkily** [comment]
I also had the same problem and I finally figured out why. I installed the Owin.Security.Saml v0.9.0 package which then automatically installed the dependent SAML2.Core v0.5.0.1 package. This older version does not have the AddByMetadataUrl method. Updating the SAML2.Core package to v0.9.0 fixed the issue.

**Comment by togakangaroo** [comment]
Any chance of this getting fixed?

**Comment by jaypeng2015** [comment]
Maybe it's time to release a new version. @elerch 
I can't get SAML2.Core 0.9.0 working with my project but the GitHub code works well.

**Comment by elerch** [comment]
Vacation day - sorry for the super-long delay. Nuget now matches df34ed8.
